protection:
  required_status_checks:
    strict: true
    contexts: []
  enforce_admins: true
  required_pull_request_reviews:
    dismissal_restrictions:
      users: []
      teams: []
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    required_approving_review_count: 2
  restrictions:
    users: []
    teams: []
    apps: []
  required_linear_history: false
  allow_force_pushes: false
  allow_deletions: false
